// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250127204102_RemoveFoodCategoryIdFromProduct")]
    partial class RemoveFoodCategoryIdFromProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);





            modelBuilder.Entity("Domain.Entities.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<int>("CuisineId")
                    .HasColumnType("int");

                b.Property<string>("Ingredient")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MenuCategoryId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.Property<int>("SalesCount")
                    .HasColumnType("int");

                b.Property<int?>("SpecialCategoryId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CuisineId");

                b.HasIndex("MenuCategoryId");

                b.HasIndex("SpecialCategoryId");

                b.ToTable("Products");
            });

            modelBuilder.Entity("Domain.Entities.Product", b =>
            {
                b.HasOne("Domain.Entities.Cuisine", "Cuisine")
                    .WithMany("Products")
                    .HasForeignKey("CuisineId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Domain.Entities.MenuCategory", "MenuCategory")
                    .WithMany("Products")
                    .HasForeignKey("MenuCategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.Entities.SpecialCategory", "SpecialCategory")
                    .WithMany("Products")
                    .HasForeignKey("SpecialCategoryId");

                b.Navigation("Cuisine");

                b.Navigation("MenuCategory");

                b.Navigation("SpecialCategory");
            });

            modelBuilder.Entity("Domain.Entities.ProductImage", b =>
            {
                b.HasOne("Domain.Entities.Product", "Product")
                    .WithMany("ProductImages")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");
            });

#pragma warning restore 612, 618
        }
    }
}
