<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controllers\" />
    <None Remove="Models\" />
    <None Remove="ViewModels\" />
    <None Remove="Areas\" />
    <None Remove="Areas\Admin\" />
    <None Remove="Areas\Admin\Controllers\" />
    <None Remove="Areas\Admin\ViewModels\" />
    <None Remove="Areas\Admin\Views\" />
    <None Remove="Areas\Admin\Views\Dashboard\" />
    <None Remove="Areas\Admin\ViewModels\Slider\" />
    <None Remove="Areas\Admin\Views\Slider\" />
    <None Remove="Views\About\" />
    <None Remove="ViewModels\Events\" />
    <None Remove="ViewModels\GalleryImage\" />
    <None Remove="Views\Menu\" />
    <None Remove="Views\BookATable\" />
    <None Remove="Views\Blog\" />
    <None Remove="Views\Shop\" />
    <None Remove="Views\Element\" />
    <None Remove="Areas\Admin\ViewModels\Award\" />
    <None Remove="Areas\Admin\Views\Award\" />
    <None Remove="Models\Enum\" />
    <None Remove="Areas\Admin\ViewModels\AwardLogo\" />
    <None Remove="Areas\Admin\Views\AwardLogo\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Models\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Areas\" />
    <Folder Include="Areas\Admin\" />
    <Folder Include="Areas\Admin\Controllers\" />
    <Folder Include="Areas\Admin\ViewModels\" />
    <Folder Include="Areas\Admin\Views\" />
    <Folder Include="Areas\Admin\Views\Dashboard\" />
    <Folder Include="wwwroot\admin\" />
    <Folder Include="Areas\Admin\ViewModels\Slider\" />
    <Folder Include="Areas\Admin\Views\Slider\" />
    <Folder Include="Views\About\" />
    <Folder Include="ViewModels\Events\" />
    <Folder Include="ViewModels\GalleryImage\" />
    <Folder Include="Views\Menu\" />
    <Folder Include="Views\BookATable\" />
    <Folder Include="Views\Blog\" />
    <Folder Include="Views\Shop\" />
    <Folder Include="Views\Element\" />
    <Folder Include="Areas\Admin\ViewModels\Award\" />
    <Folder Include="Areas\Admin\Views\Award\" />
    <Folder Include="Models\Enum\" />
    <Folder Include="Areas\Admin\ViewModels\AwardLogo\" />
    <Folder Include="Areas\Admin\Views\AwardLogo\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="wwwroot\admin\" />
    <Content Remove="wwwroot\assets\images\page-title\1.jpg" />
    <Content Remove="wwwroot\assets\images\sliders\slide-bg\12.jpg" />
    <Content Remove="wwwroot\assets\images\sliders\slide-bg\3.jpg" />
    <Content Remove="wwwroot\assets\images\sliders\slide-bg\1.jpg" />
    <Content Remove="wwwroot\assets\images\banners\4.jpg" />
    <Content Remove="wwwroot\assets\images\banners\5.jpg" />
    <Content Remove="wwwroot\assets\images\page-title\2.jpg" />
    <Content Remove="wwwroot\assets\images\team\team1.jpg" />
  </ItemGroup>
</Project>
